### ISSUE TITLE
Jest encountered an unexpected token, help needed

### ISSUE THREAD

**Issue by bboguszewski** [uittorio/jest-ts-auto-mock#10]
I'm working with RabbitMQ library `amqplib` and I have problem with mocking some object (`amqp.Message` to be exact). I have the following test:
 
```
import {Message} from 'amqplib/callback_api'
import { createMock } from "ts-auto-mock";

describe('reuse', () => {
	let mock: Message;
	
	beforeEach(() => {
		mock = createMock<Message>();
	});
	
	it('should assign the value', () => {
		expect(mock.content).toBe("");
	});
});
```

This test (and whole project) is taken from your [examples](https://github.com/Typescript-TDD/jest-ts-auto-mock/blob/master/examples/ts-jest-ttypescript/reuse/1.test.ts). 

And I still have this message:

```
Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /--path-to-project--/reuse/1.test.ts:217
        : { get: function () { return _sundefined || (_sundefined = undefined); }, set: function (_undefined) { _sundefined = _undefined; }, enumerable: true },
        ^

    SyntaxError: Unexpected token :

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)

```

Any idea how to resolve it?

**Comment by uittorio** [comment]
Hi @barthpl, thanks for reporting the issue. 

Could you please confirm which version of jest-ts-auto-mock you are using? 

If you have a project that I can see it would be easier. Otherwise you could share the jest configuration that you are using

That issue usually means that the typescript file are not parsed correctly by a compiler. Did you use ts-jest?

**Comment by bboguszewski** [comment]
@uittorio please find a code in [here](https://github.com/barthpl/Typescript-TDD-jest-ts-auto-mock-issue-10).

`package.json` content
```
{
  "name": "ts-jest-ttypescript",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "jest",
    "test:runInBand": "jest -i",
    "clearCache": "jest --clearCache"
  },
  "jest": {
    "setupFiles": [
      "<rootDir>config.ts"
    ],
    "transform": {
      ".(ts|tsx)": "ts-jest"
    },
    "testRegex": "(/src/.*|\\.(test))\\.(ts|tsx)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "json"
    ],
    "globals": {
      "ts-jest": {
        "compiler": "ttypescript"
      }
    }
  },
  "devDependencies": {
    "@types/jest": "24.0.24",
    "jest": "24.9.0",
    "jest-ts-auto-mock": "1.0.7",
    "ts-jest": "24.2.0",
    "ttypescript": "1.5.8",
    "typescript": "3.7.4"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@types/amqplib": "^0.5.13",
    "amqplib": "^0.5.5",
    "ts-auto-mock": "1.4.2"
  }
}
```

**Comment by uittorio** [comment]
@barthpl  Hi. I had a quick look. there is an issue using  this interface that is used by Message from amqplib/properties 

```ts
export interface MessagePropertyHeaders {
    "x-first-death-exchange"?: string;
    "x-first-death-queue"?: string;
    "x-first-death-reason"?: string;
    "x-death"?: XDeath[];
    [key: string]: any;
}
```

Thanks for the feedback. It could be that we don't support yet interface properties as ['name'] correctly.

I'll work on it tomorrow :)

**Comment by uittorio** [comment]
@barthpl I've opened a PR to solve this issue. 

https://github.com/Typescript-TDD/ts-auto-mock/pull/122

Once it's approved and merged I'll update jest-ts-auto-mock.

Sorry for the delay (holiday time) ahaha

Thank you again for your feedback because with this feature we've improved ts auto mock capabilities. 

Soon we will create a task to run this library against all the DefinitelyType from typescript so we can avoid waiting for issues to be opened to fix something.

**Comment by uittorio** [comment]
@barthpl jest-ts-auto-mock version 1.0.9 just released. https://www.npmjs.com/package/jest-ts-auto-mock

**Comment by bboguszewski** [comment]
@uittorio I have updated jest-ts-auto-mock version to 1.0.9 but still have the same issue. Should I do something more to have your fix working for me? As previously code is [here](https://github.com/barthpl/Typescript-TDD-jest-ts-auto-mock-issue-10).

**Comment by uittorio** [comment]
Hi :) could you try to remove ts auto mock from the dependencies in the package json? It should be a dependency of jest ts auto mock and not the consumer. Ill update the example library to not have it.

If it doesnt work just update ts auto mock to the latest. Npm install ts-auto-mock@latest

**Comment by bboguszewski** [comment]
@uittorio removing `ts-auto-mock` results with error `Cannot find module 'ts-auto-mock/transformer' from '/--path-to-project--/ts-jest-ttypescript'`. But `Npm install ts-auto-mock@latest` did a job.

Thank you for all the help.
