### ISSUE TITLE
Uses an old version of ts-auto-mock

### ISSUE THREAD

**Issue by Peeja** [uittorio/jest-ts-auto-mock#31]
It looks like `jest-ts-auto-mock` is stuck on a fairly old version of `ts-auto-mock` (`^1.5.0`). Is this package currently maintained? Or is there a technical reason it's hard to make newer features work with Jest? I'm grateful for your work, I just don't want to start relying on it for the first time if it's not getting any attention right now. :)

**Comment by uittorio** [comment]
Hi @Peeja . jest-ts-auto-mock should easily work with any version of ts-auto-mock greater than 1. ts-auto-mock is part of the peerDependencies so you can install any of them. I will have a look and update the peer dependencies

**Comment by Peeja** [comment]
Ah, that's great news! Thanks!

**Comment by uittorio** [comment]
Published a new version 2.0.0 @Peeja

**Comment by Peeja** [comment]
Fantastic! Thank you!
