### ISSUE TITLE
Support for Typescript 4 

### ISSUE THREAD

**Issue by okuuva** [uittorio/jest-ts-auto-mock#32]
Requirements list typescript@^3.2.2 as dependency. Is there any plans on supporting typescript@^4?

**Comment by uittorio** [comment]
Typescript 4 is supported by ts-auto-mock 3.X.X. I just have to update the peerDependency!! I am sorry for the delay in this issue, I've just moved house! I will try tonight to open these quick pull requests and publish a new version

**Comment by okuuva** [comment]
Hey no biggie, maintaining OSS is (almost) always voluntary job and even minor patches take time if you're busy with something else. Congrats on new home :) There was already an issue open about the peerDependency (#31) but the devDependency list also lists typescript@^3 as a dependency so I won't close this as duplicate even though they're related.

**Comment by uittorio** [comment]
Done :) published version 2.0.0 @okuuva
