### ISSUE TITLE
Jest 27 support

### ISSUE THREAD

**Issue by qdelettre** [uittorio/jest-ts-auto-mock#45]
Hi

Is there an ongoing work to support Jest 27 ?

Thanks

**Comment by uittorio** [comment]
Hello! There should not be any issues updating to jest 27, I will have a look. You can also open a PR and update the peer dependencies if you have time

**Comment by uittorio** [comment]
@qdelettre this is now released, thank you! version 2.0.1. Let me know if that works. BTW, if you need to test an unpublished version of a library you can use the npm link functionality https://docs.npmjs.com/cli/v8/commands/npm-link!!

**Comment by qdelettre** [comment]
@uittorio Ci is failling due to node 10 i suppose 🙁
I used node 14 locally. I'm travelling right now, but updating GH config to a lts version  supported by jest should fix.
