### ISSUE TITLE
Support for using together with babel/other transformers

### ISSUE THREAD

**Issue by tjespe** [uittorio/jest-ts-auto-mock#7]
I have followed the guide on how to set this up, but that caused JSX/TSX files to not be transformed correctly.  I read in the Jest configuration guide that currently only one transformer per file is supported and it seems like [it is going to stay that way](https://github.com/facebook/jest/issues/8725).

Could you add support or a guide on how to set this up without losing the other transformers?

**Comment by uittorio** [comment]
Hello @tjespe, thank you for reporting the issue. I believe as you mentioned that the issue is on jest side, it doesnt allow more than one transformer at the same time. In the issue you’ve posted they also provide an example to how to add more than one transformer. Could you please tell me which other transformer you are using so I can provide an example in jest-ts-auto-mock

**Comment by tjespe** [comment]
I was using the other default jest transforms that react-scripts had set up automatically. I don’t have the code now, but a list of the transformers is probably available in the react-scripts repository.

I fixed my problem by using `craco` to override the default settings, and put the `ts-jest` compiler as the first entry in the `transformers` object with a regex that only included `.ts` files, not `.tsx`.

**Comment by uittorio** [comment]
I'm glad you've found an alternative solution. 

I've added a [https://github.com/Typescript-TDD/ts-auto-mock/issues/107](link) to an existing issue to improve documentation for future reference.

**Comment by uittorio** [comment]
I've created an [article](https://medium.com/@vittorioguerriero/jest-with-ts-auto-mock-real-mocks-da9a181792dd) that explains how to use it with jest.. and there is also a [documented guide](https://typescript-tdd.github.io/ts-auto-mock/installation#jest--ts-jest--ttypescript) in the website
